version: 0.0
os: linux
files:
  - source: /target/myapp.jar
    destination: /home/ubuntu/my-java-app
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
