version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y maven 
  build:
    commands:
      - echo "Building the Java app..."
      - mvn clean package 
  post_build:
    commands:
      - echo "Build completed. Uploading artifacts to S3..."

artifacts:
  files:
    - target/*.jar  
  discard-paths: yes  
  base-directory: target  
